---
## Base opts
execute: 
  warning: false
editor_options: 
  chunk_output_type: console
## Extensions
filters: 
    - shinylive
format:
  html:
    ## Code
    resources: shinylive-sw.js
---

# Gráficos de distribución {#sec-plot-distribution}

Los gráficos de distribución son una forma de visualizar la distribución de los datos. En este tipo de gráficos, se muestra la frecuencia de los valores de una variable o de un conjunto de variables. Los gráficos de distribución son útiles para identificar patrones en los datos, como la presencia de valores atípicos, la simetría de la distribución, la presencia de múltiples modas, entre otros. Generalmente, los gráficos de distribución se utilizan para visualizar **una sola variable numérica** aunque en la @fig-vis-classification se muestra que también es posible visualizar **dos variables numéricas** mediante el uso de gráficos de dispersión (**scatter plot**).

En este capítulo, veremos los siguientes tipos de gráficos de distribución:

1. Histogramas (**histogram**)

2. Gráficos de densidad (**density plot**)

3. Gráficos de cajas (**box plot**)

4. Gráficos de violín (**violin plot**)

:::callout-info
Los gráficos de dispersión los veremos dentro del capítulo de gráficos de relación.
:::

Para comenzar, vamos a cargar los paquetes necesarios y a leer los datos que utilizaremos en este capítulo. 

```{r}
# Cargar paquetes
library(ggplot2)
library(readr)
# Cargar datos
inventario_tbl <- read_rds("data/inventario_prep.rds")
```


## Histogramas

Los histogramas son una forma de visualizar la distribución de una variable numérica. En un histograma, los valores de la variable se agrupan en intervalos y se muestra la frecuencia de los valores en cada intervalo. Los histogramas son útiles para identificar la forma de la distribución de los datos, la presencia de valores atípicos y la presencia de múltiples modas.

Para crear un histograma en `ggplot2`, utilizamos la función `geom_histogram()`. Tiene dos argumentos de gran importancia:

- `bins`: número de intervalos en los que se agruparán los datos. Si no se especifica, `{ggplot2}` utilizará 30 intervalos.

- `binwidth`: ancho de los intervalos. Si se especifica, `{ggplot2}` calculará el número de intervalos automáticamente.

:::callout-note
Estos dos argumentos son mutuamente excluyentes. Si se especifica `bins`, `{ggplot2}` ignorará `binwidth`.
:::

Vamos a ver la diferencia entre estos dos argumentos viendo la distribución diamétrica de los datos de inventario.

```{shinylive-r}
#| standalone: true
#| viewerHeight: 300

## Load packages
library(bslib)
library(ggplot2)
library(readr)
library(shiny)

## UI
ui <- page_sidebar(
    sidebar = sidebar(
        open = "open",
        sliderInput("bins", "Número de intervalos", min = 1, max = 100, value = 30),
    ),
    h2("Test"),
    plotOutput("plot", width = 300),
    h3("OK")
)

## Server
server <- function(input, output, session) {

    ## Load data
    inventario_tbl <- read_rds("data/inventario_prep.rds")

    ## Plot
    output$plot <- renderPlot({
        ggplot(inventario_tbl, aes(x = dbh_mm / 10)) +
            geom_histogram(bins = input$bins, fill = "#0073C2FF", color = "white") +
            labs(title = "Distribución diamétrica", x = "DBH (cm)", y = "Frecuencia") +
            theme_minimal()
    }, res = 96)
}

## Run app
shinyApp(ui = ui, server = server)
```














