## Project type
project:
  type: book
  resources: 
    - shinylive-sw.js

## Book options
book:
  ## Book metadata
  title: "Fundamentos de programación con R"
  abstract: "Libro de programación en R correspondiente al curso de Fundamentos de Programación con R del Máster Geoforest de la Universidad de Córdoba."
  #description: "Descripcion..."
  author: "Adrián Cidre"
  date: today
  ## Book opts
  repo-url: https://github.com/Cidree/MG_fundamentosR
  issue-url: https://github.com/Cidree/MG_fundamentosR/issues
  site-url: https://fundamentos-r.netlify.app/
  cover-image: assets/img/logo-geoforest.png
  reader-mode: true
  language: es
  license: "CC BY-SA"
  ## Book sidebar
  sidebar:
    id: book_sidebar
    logo: assets/img/logo-geoforest.png
    style: docked
    # foreground: light
    background: light
    alignment: center
  ## Footer
  page-footer:
    left: |
      Fundamentos de Programación con R (1e).<br>Adrián Cidre, 2024
    right: |
      Este libro ha sido escrito con <a href="https://quarto.org/" target="_blank">Quarto</a>.
  ## Book structure
    center: |
        <a href="https://mastergeoforest.es//" target="_blank">Máster Geoforest</a><br>
        <a href="https://www.uco.es/eguiado/guias/2023-24/20286es_2023-24.pdf" target="_blank">Guía docente</a><br>
        <a href="https://moodle.uco.es/m2223/" target="_blank">Moodle</a>
  ## Chapters
  chapters:
    - index.qmd
    
    - part: chapters/1001_visualization.qmd
      chapters:
        - chapters/1002_introduction.qmd
        - chapters/1003_first_steps.qmd
        - chapters/1004_components.qmd
    
    - part: chapters/1101_visualization_types.qmd
      chapters:
        - chapters/1102_distribution.qmd
        - chapters/1103_relationship.qmd
        - chapters/1104_comparison.qmd
        
    - part: chapters/1201_components.qmd
      chapters:
        - chapters/1202_scales.qmd
        - chapters/1203_coords.qmd
        - chapters/1204_facets.qmd
        - chapters/1205_themes.qmd
        
  ## Appendices
  appendices:
    - chapters/installation.qmd

## Format specific options
format:
  html:
    ## Code
    code-fold: true
    highlight-style: kate
    code-copy: hover
    code-link: true
    code-block-border-left: true
    ## Theming
    theme:
      light: [cosmo, assets/styles/light-style.scss, assets/styles/common-styles.scss]
      dark: [darkly, assets/styles/dark-style.scss, assets/styles/common-styles.scss]
    ## References and similars
    bibliography: references.bib
    lang: es
    ## Figuras
    fig-align: center
    crossref: 
      fig-title: "Fig."
    ## Page layout
    grid: 
      sidebar-width: 300px
      content-mode: auto
      gutter-width: 3rem

## Code executions opts
execute: 
  warning: false
  freeze: auto

## Extensions
lightbox: auto
filters: 
    - shinylive
webr:
  repos:
    - https://cidree.github.io/MG_datasets
