project:
  type: book

book:
  ## Book metadata
  title: "Fundamentos de programación con R"
  abstract: "Libro de programación en R correspondiente al curso de Fundamentos de Programación con R."
  description: "Descripcion..."
  author: "Adrián Cidre"
  date: "2024/05/28"
  ## Book opts
  repo-url: https://github.com/Cidree/test_book/
  issue-url: https://github.com/Cidree/test_book/issues
  site-url: https://cidree.github.io/test_book/
  cover-image: assets/img/logo-geoforest.png
  reader-mode: true
  language: es
  ## Book sidebar
  sidebar:
    id: book_sidebar
    logo: assets/img/logo-geoforest.png
    style: docked
    # foreground: light
    background: light
    alignment: center
  ## Footer
  page-footer:
    left: |
      Fundamentos de Programación con R (1e). Adrián Cidre, 2024
    right: |
      Este libro ha sido escrito con <a href="https://quarto.org/" target="_blank">Quarto</a>.
  ## Book structure
    center: |
      <a href="https://mastergeoforest.es//" target="_blank">Máster Geoforest</a><br>
      <a href="https://www.uco.es/eguiado/guias/2023-24/20286es_2023-24.pdf" target="_blank">Guía docente</a><br>
      <a href="https://moodle.uco.es/m2223/" target="_blank">Moodle</a>
  ## Chapters
  chapters:
    - index.qmd
    - chapters/introduction.qmd
    - chapters/testing.qmd
    - chapters/references.qmd
  ## Appendices
  appendices:
    - chapters/installation.qmd

bibliography: references.bib
lang: es

format:
  html:
    ## Code
    highlight-style: tango
    code-copy: hover
    code-link: true
    code-block-border-left: true
    ## Theming
    theme:
      light: [cosmo, assets/styles/light-style.scss]
      dark: [darkly, assets/styles/dark-style.scss]
