## Book options
project:
  type: book

book:
  ## Book metadata
  title: "Fundamentos de programación con R"
  abstract: "Libro de programación en R correspondiente al curso de Fundamentos de Programación con R del Máster Geoforest de la Universidad de Córdoba."
  #description: "Descripcion..."
  author: "Adrián Cidre"
  date: "2024/05/28"
  ## Book opts
  repo-url: https://github.com/Cidree/test_book/
  issue-url: https://github.com/Cidree/test_book/issues
  site-url: https://cidree.github.io/test_book/
  cover-image: assets/img/logo-geoforest.png
  reader-mode: true
  language: es
  ## Book sidebar
  sidebar:
    id: book_sidebar
    logo: assets/img/logo-geoforest.png
    style: docked
    # foreground: light
    background: light
    alignment: center
  ## Footer
  page-footer:
    left: |
      Fundamentos de Programación con R (1e). Adrián Cidre, 2024
    right: |
      Este libro ha sido escrito con <a href="https://quarto.org/" target="_blank">Quarto</a>.
  ## Book structure
    center: |
        <a href="https://mastergeoforest.es//" target="_blank">Máster Geoforest</a><br>
        <a href="https://www.uco.es/eguiado/guias/2023-24/20286es_2023-24.pdf" target="_blank">Guía docente</a><br>
        <a href="https://moodle.uco.es/m2223/" target="_blank">Moodle</a>
  ## Chapters
  chapters:
    - index.qmd
    
    - part: 1001_visualization.qmd
      chapters:
        - 1002_introduction.qmd
        - 1003_first_steps.qmd
        - 1004_components.qmd
    
    - part: 1101_visualization_types.qmd
      chapters:
        - 1102_distribution.qmd
        
    - chapters/testing.qmd
  ## Appendices
  appendices:
    - chapters/installation.qmd

## Code executions opts
execute: 
  warning: false
  freeze: auto

## Extensions
filters: 
    - shinylive
lightbox: auto

format:
  html:
    ## Code
    resources: shinylive-sw.js
    highlight-style: tango
    code-copy: hover
    code-link: true
    code-block-border-left: true
    ## Theming
    theme:
      light: [cosmo, assets/styles/light-style.scss, assets/styles/common-styles.scss]
      dark: [darkly, assets/styles/dark-style.scss, assets/styles/common-styles.scss]
    ## References and similars
    bibliography: references.bib
    lang: es
    ## Figuras
    fig-align: center
    crossref: 
      fig-title: "Fig."
    ## Page layout
    grid: 
      sidebar-width: 300px
      content-mode: auto
      gutter-width: 3rem
