{
  "hash": "88183e680e27013273c7bc8e4664a88a",
  "result": {
    "engine": "knitr",
    "markdown": "---\nexecute: \n  warning: false\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n# Primeros pasos con ggplot2\n\n`{ggplot2}` es un paquete de R que permite crear gráficos de forma sencilla y flexible. A diferencia de muchos paquetes de R u otros software, `{ggplot2}` se basa en una gramática de gráficos [@gog] que permite crear gráficos siguiendo una serie de reglas basadas en la construcción de gráficos a partir de capas y otros componentes.\n\n## Objetivos {#sec-vis-objectives}\n\n-   Entender la gramática de gráficos y su implicación dentro de `{ggplot2}`\n\n-   Estudiar los componentes que formar un gráfico en `{ggplot2}`\n\n-   Crear gráficos sencillos\n\n-   Entender como funciona la herencia de datos y estéticas\n\n-   Estudiar la diferencia entre mapear y asignar una estética\n\nEn esta sección, trabajaremos con los siguientes paquetes:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(skimr)\nlibrary(readr)\n```\n:::\n\n\n\n\n## Datos de trabajo {#sec-vis-data}\n\nAntes de comenzar a trabajar con `{ggplot2}`, vamos a explorar los datos con los que vamos a trabajar. En este caso, vamos a utilizar un conjunto de datos de ejemplo que contiene información sobre una serie de árboles. Para cargar los datos, utilizaremos la función `read_rds()` del paquete `{readr}`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_tbl <- read_rds(\"data/inventario_prep.rds\")\n```\n:::\n\n\n\n\nUna vez que hemos cargado los datos, vamos a utilizar la función `skim` del paquete `{skimr}` para obtener un resumen de los datos:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskim(inventario_tbl)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |               |\n|:------------------------|:--------------|\n|Name                     |inventario_tbl |\n|Number of rows           |1540           |\n|Number of columns        |4              |\n|_______________________  |               |\n|Column type frequency:   |               |\n|factor                   |2              |\n|numeric                  |2              |\n|________________________ |               |\n|Group variables          |None           |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                     |\n|:-------------|---------:|-------------:|:-------|--------:|:------------------------------|\n|id_plots      |         0|             1|FALSE   |       27|17: 111, 11: 91, 5: 89, 14: 79 |\n|nombre_ifn    |         0|             1|FALSE   |        2|Pin: 1302, Pin: 238            |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|   mean|    sd|   p0|    p25|    p50|    p75|   p100|hist  |\n|:-------------|---------:|-------------:|------:|-----:|----:|------:|------:|------:|------:|:-----|\n|dbh_mm        |        12|          0.99| 184.85| 50.97| 65.0| 153.75| 177.00| 207.00| 531.00|▃▇▁▁▁ |\n|height_m      |      1120|          0.27|   9.49|  3.27|  3.3|   7.39|   8.57|  10.47|  21.99|▂▇▂▁▁ |\n\n\n:::\n:::\n\n\n\n\nEsta función nos proporciona información sobre las variables del conjunto de datos, incluyendo el tipo de variable, el número de observaciones, el número de valores faltantes (NA), la media, la desviación estándar, los valores mínimos y máximos, y los cuartiles.\n\nTenemos 2 variables numéricas que son el diámetro y la altura de los árboles, y 2 variables categóricas que son la especie (*Pinus nigra* o *Pinus sylvestris*) y un identificador de la parcela de inventario (27 parcelas distintas). Para el diámetro, tenemos un total de 12 valores ausentes (NA) que son aproximadamente un 1% de los datos. Para la altura, tenemos 1120 valores ausentes, que son aproximadamente un 73% de los datos. En este sentido, es importante tener en cuenta que los valores ausentes pueden afectar a los análisis y visualizaciones que realicemos con los datos.\n\n::: callout-note\nAunque estos datos tengan una estructura muy sencilla, nos servirán a la perfección para los objetivos de este curso. Nuestro objetivo será entender la gramática de gráficos como una base fundamental que nos permitirá transmitir el mensaje que deseemos con nuestros datos.\n:::\n\n## Gramática de gráficos {#sec-gog}\n\nLa gramática de gráficos es un conjunto de reglas que definen cómo se pueden construir gráficos a partir de componentes básicos, y fue creada por @gog. La idea de crear una gramática de gráficos es que, al igual que en la gramática de un idioma, se pueden combinar diferentes elementos para crear gráficos complejos. Cuando aprendemos a hablar un idioma, aprendemos las reglas gramaticales y el vocabulario, y con estos elementos podemos crear frases y textos. De la misma forma, al aprender la gramática de gráficos, podemos crear gráficos complejos a partir de componentes básicos.\n\nPosteriormente se creó `{ggplot2}` [@layered-grammar], que utiliza las reglas gramaticales de la gramática de gráficos para crear gráficos en R. `{ggplot2}` se basa en la idea de que un gráfico se puede construir a partir de **capas**, y cada capa se puede añadir al gráfico para añadir información adicional.\n\n## Componentes {#sec-components}\n\nLa gramática de gráficos tiene una serie de componentes diferenciados [@fig-layers] que se definen en @layered-grammar. Estos componentes son:\n\n-   **Datos (*data*)**: conjunto de datos que utilizamos para generar el gráfico.\n\n-   **Geometrías (*geom*)**: se refiere a la forma de representación de nuestros datos. Algunos ejemplos de geometrías son: puntos, líneas, histograma, diagramas de caja, etc.\n\n-   **Estéticas (*aes*)**: también denominados *aesthetic mappings*. Se refiere a los elementos que definen la estética de las geometrías. Si ponemos el ejemplo de un gráfico de puntos (*scatter plot*), las estéticas pueden ser: su forma (punto, rectángulo, triángulo...), su tamaño, color, transparencia ...\n\n-   **Transformaciones estadísticas (*stat*)**:se refiere al estadístico utilizado para resumir nuestros datos. Por ejemplo, para crear un histograma resumimos nuestros datos en intervalos (*bins*) y contamos el número de observaciones que existen dentro de este intervalo. Este componente es más avanzado que el resto, por lo que trabajaremos solamente con los valores que vienen por defecto.\n\n-   **Escalas (*scale*)**: transforman los valores de los datos en estéticas. Nos permiten controlar los colores, tamaños, formas, etc. También nos permiten controlar aspectos de las leyendas y ejes.\n\n::: callout-important\nExiste una escala por cada estética utilizada.\n:::\n\n-   **Facetas (*facets*)**: consiste en generar subgráficos según un atributo. Por ejemplo, utilizando nuestros datos de inventario, podemos generar un gráfico de puntos donde representemos la relación diámetro-altura para todos los datos, o bien podemos generar facetas que generen un gráfico por cada una de las especies (es decir, un *scatter plot* para *P. nigra* y otro distinto para *P. sylvestris*).\n\n-   **Coordenadas (*coord*)**: sistema de coordenadas utilizado para mapear los datos. Por defecto y normalmente, utilizaremos el sistema de coordenadas cartesiano. Otros sistemas disponibles son el sistema de coordenadas polares (que nos permiten crear los increíbles gráficos circulares), o también sistemas de referencia de coordenadas para generar mapas (sí, con `{ggplot2}` podemos generar mapas🗺️).\n\n-   **Tema (*theme*)**: nos permite controlar todos los aspectos relacionados con la apariencia del gráfico, como puede ser la fuente de texto, tamaño de fuente, posición de elementos como la leyenda, colores de relleno, etc.\n\n![Componentes principales de la gramática de gráficos](images/layers.png){#fig-layers fig-align=\"center\"}\n\nFinalmente, podemos definir una **capa** como la combinación de datos, estéticas, geometrías y transformaciones estadísticas [@book-ggplot2], y en la mayoría de las ocasiones, estos cuatro componentes se especificarán dentro de una función que comienza por `geom_*`, aunque los datos y las estéticas también se pueden especificar dentro de la función `ggplot()`. No os preocupéis, pronto veremos las diferencias entre estas opciones.\n\n::: callout-important\nUn mismo gráfico puede contener más de una capa y estas capas pueden (o no) compartir los mismo datos:\n\n-   Capa 1: utiliza los datos de inventario, como estéticas utiliza las variables `DBH_mm` y `height_m`, la geometría de punto y como transformación estadística utiliza **identity**. Esta transformación es utilizada por muchas geometrías y significa que va a utilizar los valores tal cual aparecen en la tabla de datos, sin realizar ninguna transformación. En términos matemáticos significa que $f(x)= x$.\n\n-   Capa 2: utiliza los datos de inventario, como estéticas utiliza las variables `DBH_mm` y `height_m`, la geometría de línea y como transformación estadística utiliza **smooth**. Esta transformación utiliza un método de suavizado (por defecto una [Regresión Local (](https://es.wikipedia.org/wiki/Regresi%C3%B3n_local)[LOESS](https://es.wikipedia.org/wiki/Regresi%C3%B3n_local){target=\"_blank\"}[)](https://es.wikipedia.org/wiki/Regresi%C3%B3n_local)) donde se genera una línea que aproxima la tendencia de los datos.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\nEl tipo de gráfico viene definido por dos elementos: el tipo de geometría y la transformación estadística. Por poner un ejemplo relacionado con el anterior:\n\n-   **Gráfico de líneas**: se define por una geometría de línea y una transformación estadística ***identity*** (`geom_line(stat = \"identity\")`).\n\n-   **Gráfico suavizado**: utiliza la geometría de línea y una transformación estadística ***smooth*** (`geom_line(stat = \"smooth\")`).\n\nNo obstante, los gráficos comunes como el gráfico suavizado vienen incluidos en `{ggplot2}` a través de una función que utiliza la transformación estadística adecuada por defecto, y solamente nos hará falta llamar a la función adecuada sin utilizar el argumento `stat`:\n\n| Función       | T.E. por defecto |\n|---------------|------------------|\n| geom_line()   | identity         |\n| geom_smooth() | smooth           |\n\n## Ejemplo rápido {#sec-first-example}\n\nPara digerir los conceptos anteriores, vamos a ver un ejemplo rápido. Para este ejemplo, vamos a eliminar los valores ausentes, ya que el objetivo es solamente entender los conceptos anteriores y no generar un gráfico para publicar.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl <- na.omit(inventario_tbl)\nprint(inventario_completo_tbl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 418 × 4\n   id_plots dbh_mm height_m nombre_ifn      \n   <fct>     <int>    <dbl> <fct>           \n 1 0           296     9.26 Pinus sylvestris\n 2 0           303    10.1  Pinus sylvestris\n 3 0           105     5.48 Pinus sylvestris\n 4 0           138     7.07 Pinus nigra     \n 5 0           153     7.54 Pinus sylvestris\n 6 0           233     9.60 Pinus sylvestris\n 7 0           140     7.01 Pinus sylvestris\n 8 0           200     7.36 Pinus sylvestris\n 9 0           210    10.1  Pinus sylvestris\n10 0           142     6.25 Pinus sylvestris\n# ℹ 408 more rows\n```\n\n\n:::\n:::\n\n\n\n\nDe este modo nos quedamos con 418 observaciones.\n\n::: panel-tabset\n## Líneas\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m)\n    ) +\n    geom_line()\n```\n\n::: {.cell-output-display}\n![Ejemplo básico de gráfico de líneas](1003_first_steps_files/figure-html/fig-example-line-1.png){#fig-example-line width=672}\n:::\n:::\n\n\n\n\n## Suavizado 1\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m)\n    ) +\n    geom_line(\n        stat = \"smooth\"\n    )\n```\n\n::: {.cell-output-display}\n![Ejemplo básico de línea suavizada con geom_line()](1003_first_steps_files/figure-html/fig-example-suave1-1.png){#fig-example-suave1 width=672}\n:::\n:::\n\n\n\n\n## Suavizado 2\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m)\n    ) +\n    geom_smooth()\n```\n\n::: {.cell-output-display}\n![Ejemplo básico de línea suavizada con geom_smooth()](1003_first_steps_files/figure-html/fig-example-suave2-1.png){#fig-example-suave2 width=672}\n:::\n:::\n\n\n\n:::\n\nCompara las tres gráficas. En @fig-example-line no utilizamos el argumento `stat` ya que el que viene por defecto es `identity`. Del mismo modo, en @fig-example-suave2 tampoco es necesario utilizar el argumento ya que `stat = \"smooth\"` viene por defecto.\n\n::: callout-note\nEn este curso no vamos a trabajar con transformaciones estadísticas en mayor profundidad. Esta sección solamente quiere remarcar que detrás de cada geometría existe una transformación estadística que viene dada por defecto.\n:::\n\nTambién te habrás dado cuenta de que no hemos utilizado los componentes: facetas, escalas, coordenadas ni tema. Esto se debe a que estos componentes **siempre**, en **todos los gráficos** tienen un valor por defecto. Pero todo a su tiempo. Vamos a empezar desengranando el código anterior. Para tener una idea de los argumentos que estamos utilizando vamos a comparar los siguientes gráficos derivados de @fig-example-suave2:\n\n::: panel-tabset\n## Método 1\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n    data    = inventario_completo_tbl,\n    mapping = aes(x = dbh_mm, y = height_m)\n) +\n    geom_smooth()\n```\n\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n## Método 2\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(inventario_completo_tbl, aes(x = dbh_mm, y = height_m)) +\n    geom_smooth()\n```\n\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\n## Método 3\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n    inventario_completo_tbl, \n    aes(x = dbh_mm, y = height_m)\n) +\n    geom_smooth()\n```\n\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n\n## Método 4\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m)\n    ) +\n    geom_smooth()\n```\n\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\nComo veis, el resultado es exactamente el mismo. Normalmente utilizaremos el *pipe operator* (`|>` o `%>%`) como hacemos en el método 4 para inyectar los datos en el primer argumento de la función `ggplot()` que es `data`. El argumento `mapping` también se sabe perfectamente que es el segundo argumento de la función, por lo que no es necesario escribir `mapping = ...` si no directamente `aes(...)`. En resumen, cualquier método de escritura de código de los anteriores se adecua en mayor o menor medida a los principios de diseño ordenado [@tidy-data]. No obstante, los métodos más adecuados serán los métodos 3 y 4 ya que nos ayudarán a que nuestro código sea más legible dado que la indentación nos ayuda a ver a qué función pertenece cada argumento y hará que nuestro código sea mucho más fácil de leer y mantener. Finalmente, para añadir componentes a nuestro gráfico utilizamos el operador matemático `+`.\n\n::: callout-warning\nDesgraciadamente, mucha gente utiliza el método 2 para escribir código. Aunque en el ejemplo anterior no es algo grave, es una mala costumbre para muchos otros casos. Entiendes el siguiente código?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(select(filter(inventario_completo_tbl, dbh_mm >= 300), dbh_mm:nombre_ifn), nombre_ifn == \"Pinus sylvestris\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 29 × 3\n   dbh_mm height_m nombre_ifn      \n    <int>    <dbl> <fct>           \n 1    303     10.1 Pinus sylvestris\n 2    309     10.3 Pinus sylvestris\n 3    494     14.3 Pinus sylvestris\n 4    335     18.9 Pinus sylvestris\n 5    300     12.3 Pinus sylvestris\n 6    326     15.1 Pinus sylvestris\n 7    325     14.7 Pinus sylvestris\n 8    343     14.9 Pinus sylvestris\n 9    329     11.6 Pinus sylvestris\n10    328     18.9 Pinus sylvestris\n# ℹ 19 more rows\n```\n\n\n:::\n:::\n\n\n\n\nY si lo escribo de este modo?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(\n    select(\n        filter(\n            inventario_completo_tbl, dbh_mm >= 300\n        ), \n        dbh_mm:nombre_ifn), \n    nombre_ifn == \"Pinus sylvestris\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 29 × 3\n   dbh_mm height_m nombre_ifn      \n    <int>    <dbl> <fct>           \n 1    303     10.1 Pinus sylvestris\n 2    309     10.3 Pinus sylvestris\n 3    494     14.3 Pinus sylvestris\n 4    335     18.9 Pinus sylvestris\n 5    300     12.3 Pinus sylvestris\n 6    326     15.1 Pinus sylvestris\n 7    325     14.7 Pinus sylvestris\n 8    343     14.9 Pinus sylvestris\n 9    329     11.6 Pinus sylvestris\n10    328     18.9 Pinus sylvestris\n# ℹ 19 more rows\n```\n\n\n:::\n:::\n\n\n\n\nY de este?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    filter(dbh_mm >= 300) |> \n    select(dbh_mm:nombre_ifn) |> \n    filter(nombre_ifn == \"Pinus sylvestris\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 29 × 3\n   dbh_mm height_m nombre_ifn      \n    <int>    <dbl> <fct>           \n 1    303     10.1 Pinus sylvestris\n 2    309     10.3 Pinus sylvestris\n 3    494     14.3 Pinus sylvestris\n 4    335     18.9 Pinus sylvestris\n 5    300     12.3 Pinus sylvestris\n 6    326     15.1 Pinus sylvestris\n 7    325     14.7 Pinus sylvestris\n 8    343     14.9 Pinus sylvestris\n 9    329     11.6 Pinus sylvestris\n10    328     18.9 Pinus sylvestris\n# ℹ 19 more rows\n```\n\n\n:::\n:::\n\n\n\n\nComo ves, tres formas de escribir el mismo código aumentando la legibilidad del mismo. Estos principios se utilizarán a lo largo de este curso. Una lectura muy recomendable es [The tidyverse style guide](https://style.tidyverse.org/index.html){target=\"_blank\"}.\n:::\n\n## Herencia de estéticas {#sec-inheritance-aes}\n\nVamos a continuar con el ejemplo de la línea suavizada. Vamos a añadir otra capa donde se muestre la distribución de las observaciones con una geometría de punto:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m)\n    ) +\n    geom_point() +\n    geom_smooth()\n```\n\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\nEn este ejemplo estamos viendo una propiedad **MUY IMPORTANTE** en relación a la generación de gráficos con `{ggplot2}`. Dentro de la función `ggplot()` introducimos las estéticas y los datos. En siguiente lugar, las geometrías **heredan** estos elementos. Es decir, este gráfico podría ser algo más verboso del siguiente modo:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n    geom_point(\n        data = inventario_completo_tbl,\n        aes(x = dbh_mm, y = height_m)\n    ) +\n    geom_smooth(\n        data = inventario_completo_tbl,\n        aes(x = dbh_mm, y = height_m)\n    ) \n```\n\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n\nEn este caso, estamos especificando los datos y las estéticas en cada una de las geometrías. Aunque esto es posible, no es recomendable ya que aumenta la longitud del código y puede llevar a errores si no se especifican correctamente los datos y las estéticas en cada una de las geometrías. No obstante, en muchos casos es necesario especificar los datos y las estéticas en cada una de las geometrías, ya que pueden utilizar estéticas diferentes o incluso datos diferentes. Vamos a ver un caso sencillo donde queremos representar la relación entre el diámetro y la altura de los árboles, pero queremos que los puntos de una especie sean de un color diferente a los de la otra especie. Vamos a ver una serie de ejemplos:\n\n::: panel-tabset\n## Color - Todos\n\nEn este caso introducimos la estética `color` dentro de la función de `ggplot()`. En este caso **todas las geometrías** heredan las estéticas:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m, color = nombre_ifn)\n    ) +\n    geom_point() +\n    geom_smooth() \n```\n\n::: {.cell-output-display}\n![Ejemplo de scatter plot y línea de tendencia con estética de color para ambas geometrías](1003_first_steps_files/figure-html/fig-example-color-combined-1.png){#fig-example-color-combined width=672}\n:::\n:::\n\n\n\n\n## Color - Puntos\n\nEn este otro caso, introducimos la estética `color` solamente dentro de la función `geom_point()`, por lo que solamente los puntos utilizan esta estética:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m)\n    ) +\n    geom_point(aes(color = nombre_ifn)) +\n    geom_smooth()\n```\n\n::: {.cell-output-display}\n![Ejemplo de scatter plot y línea de tendencia con estética de color para la geometría de punto](1003_first_steps_files/figure-html/fig-example-color-point-1.png){#fig-example-color-point width=672}\n:::\n:::\n\n\n\n\n## Color - Smooth\n\nEn este último caso, añadimos la estética `color` a función `geom_smooth()`, por lo que solamente se colorean las líneas de tendencia:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m)\n    ) +\n    geom_point() +\n    geom_smooth(aes(color = nombre_ifn))\n```\n\n::: {.cell-output-display}\n![Ejemplo de scatter plot y línea de tendencia con estética de color para la geometría de la línea de tendencia](1003_first_steps_files/figure-html/fig-example-color-smooth-1.png){#fig-example-color-smooth width=672}\n:::\n:::\n\n\n\n:::\n\nTambién puedes ver que en los ejemplos anteriores, la geometría de punto la escribimos antes que la línea de tendencia. De este modo se dibujan en el gráfico, primero los puntos, y en siguiente lugar se dibuja la línea de tendencia sobre los puntos.\n\n## Mapear y asignar estéticas {#sec-map-assign-aes}\n\nPara finalizar este capítulo, vamos a ver dos conceptos que al principio pueden parecer un poco confusos, pero que veréis que tienen todo el sentido del mundo dentro de la gramática de gráficos. Vamos a comenzar viendo estas dos frases que inicialmente no tendrán mucho sentido, pero que entenderemos al final de esta sección:\n\n-   Mapeamos estéticas a variables\n\n-   Asignamos estéticas a valores constantes\n\nVamos a seguir trabajando con la geometría de puntos, ya que es una de las más sencillas para aprender la teoría. Si buscáis en la documentación oficial de las funciones `geom_*`, encontraréis una sección de estéticas como la que se muestra en la @fig-aes-point:\n\n![Estétitcas de la geometría de punto (geom_point)](images/esteticas-punto.png){#fig-aes-point fig-align=\"center\"}\n\n::: callout-important\nTodas las geometrías tienen una serie de estéticas obligatorias y otras opcionales. Para la geometría de punto las obligatorias son **x** e **y**\n:::\n\nTODAS estas estéticas se pueden mapear a variables, es decir, todas pueden ir dentro de la función `aes(x, y, alpha, color, fill ...)`. Siempre que vayan dentro de la función `aes()`, estaremos mapeando la estética a una variable, y por lo tanto, el valor de la estética debe ser una variable de nuestros datos como en el siguiente exagerado ejemplo:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(\n            x     = dbh_mm,\n            y     = height_m,\n            color = nombre_ifn,\n            shape = nombre_ifn,\n            size  = height_m\n        )\n    ) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n\nSin embargo, algunas de las estéticas también se pueden **asignar a valores constantes**. Es decir, en lugar de generar un color de punto por cada especie, podemos elegir que todos los puntos sean de color verde oscuro. O que la forma de todos los puntos sea triangular. En este caso hablamos de asignar constantes, y las estéticas se escriben **dentro de la función de `geom_*` y fuera de `aes()`**:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m)\n    ) +\n    geom_point(\n        color = \"darkgreen\",\n        shape = \"triangle\",\n        size  = 3\n    )\n```\n\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n\nEn este sentido, algo que **NO** podemos hacer y que suele ser un fallo común al empezar con `{ggplot2}` es lo siguiente:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m)\n    ) +\n    geom_point(\n        color = nombre_ifn\n    )\n```\n:::\n\n\n\n\nNos dará el error \"*Error : objeto 'nombre_ifn' no encontrado*\". Como `color` está fuera de `aes()`, la función está buscando si en el entorno existe el objeto `nombre_ifn`. Para entender este concepto, vamos a ver el siguiente código:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Asignar un color a un objeto\nnombre_ifn <- \"#456435\"\n## Gráfico\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m)\n    ) +\n    geom_point(\n        color = nombre_ifn\n    )\n```\n\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\n\nCuando una estética se encuentra fuera de `aes()`, no busca `nombre_ifn` dentro de las columnas de los datos, si no que lo busca en el *Global Environment*. Finalmente, tampoco podemos introducir constantes dentro de `aes()`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m, color = \"blue\")\n    ) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n\nEsto no funciona porque lo que hace es crear una variable constante cuyos valores son \"blue\". Es decir, esto es equivalente a:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninventario_completo_tbl |> \n    mutate(\n        colour = \"blue\"\n    ) |> \n    ggplot(\n        aes(x = dbh_mm, y = height_m, color = colour)\n    ) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](1003_first_steps_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n\nEs decir, no tiene nada de sentido. Para finalizar, vamos a resumir esta sección de nuevo en las frases que veíamos al inicio:\n\n-   Mapeamos estéticas a variables\n\n-   Asignamos estéticas a valores constantes\n\n\n## Referencias {.unnumbered}\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "1003_first_steps_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}